"""fix accuracy score column

Revision ID: 0f3d1a707349
Revises: 0e50e0878a45
Create Date: 2026-02-23 14:33:05.211774

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f3d1a707349'
down_revision = '0e50e0878a45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.alter_column('accuracy_score',
               existing_type=mysql.DECIMAL(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.alter_column('accuracy_score',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=mysql.DECIMAL(precision=5, scale=4),
               existing_nullable=True)

    # ### end Alembic commands ###
