"""fix score columns

Revision ID: 8e4780812d54
Revises: 0f3d1a707349
Create Date: 2026-02-23 14:34:15.681241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e4780812d54'
down_revision = '0f3d1a707349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_decision_log', schema=None) as batch_op:
        batch_op.alter_column('confidence_score',
               existing_type=mysql.DECIMAL(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
        batch_op.alter_column('market_stress_score',
               existing_type=mysql.DECIMAL(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
        batch_op.alter_column('risk_index',
               existing_type=mysql.DECIMAL(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_decision_log', schema=None) as batch_op:
        batch_op.alter_column('risk_index',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=mysql.DECIMAL(precision=5, scale=4),
               existing_nullable=True)
        batch_op.alter_column('market_stress_score',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=mysql.DECIMAL(precision=5, scale=4),
               existing_nullable=True)
        batch_op.alter_column('confidence_score',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=mysql.DECIMAL(precision=5, scale=4),
               existing_nullable=True)

    # ### end Alembic commands ###
